"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.featureEvents = exports.featureNeedcar = exports.featureMovies = exports.featureCurrency = exports.featureTranslate = exports.featureWeather = exports.featureTrip = exports.featurePayment = exports.featureExpense = exports.featureMap = exports.featureChecklist = exports.featureAuth = exports.featureNote = exports.featureCore = exports.featureAnalytics = void 0;
exports.featureAnalytics = 'analytics';
exports.featureCore = 'core';
exports.featureNote = 'note';
exports.featureAuth = 'auth';
exports.featureChecklist = 'checklist';
exports.featureMap = 'map';
exports.featureExpense = 'expense';
exports.featurePayment = 'payment';
exports.featureTrip = 'trip';
exports.featureWeather = 'weather';
exports.featureTranslate = 'translate';
exports.featureCurrency = 'currency';
exports.featureMovies = 'movies';
exports.featureNeedcar = 'needcar';
exports.featureEvents = 'events';
